name: analyse
on: [push]
jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run NPM
        run: npm i
      - name: ESLint check
        run: make lint
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: 61f5385763064e8ae7a5d1129bc1e7b3e14210124986a07cf9e7d5b7e17801a1
        with:
          coverageCommand: make test-coverage
          debug: true
